name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: base
        uses: jackvvl/metrics@master
        with:
          token: ${{ secrets.TOKEN_PERFIL }}
#comienzo de las cositas importantes
          user: jackvvl
          template: classic
          config_display: columns
          base: header
          commits_authoring: jackvvl
          config_timezone: America/Argentina
          #acá las cosas (revisar)
          
          #achivements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
                    
          #coding habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_trim: yes
          
          #?
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          #languages
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 16
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_lines: yes
                  
          
          
          
          #starred repositories
          plugin_stars: yes
          plugin_stars_limit: 2
          
          
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          
          plugin_traffic: yes
          repositories_forks: yes
