name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
concurrency:
  group: metrics
  
jobs:
  resources: 
    name: Generate SVG resources
    runs-on: ubuntu-latest
    steps:
    
      - name: Generate SVG resources
        if: always()
        uses: jackvvl/metrics@master
        with:
          # Common config
          user: jackvvl
          token: ${{ secrets.TOKEN_PERFIL }}
          committer_branch: main
          committer_message: Update ${filename} - [GitHub Action]
          config_timezone: America/Argentina
          
#comienzo de las cositas importantes q no cambie
          template: classic
          config_display: columns
          base: header, repositories, community
          commits_authoring: jackvvl
          extras_css: |  # Make it prettier
            * { font-size: 13px; }
            h2 { margin: 2px 5px 6px !important; }
            
          #acá las cosas (revisar)
          
          #languages
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 16
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_lines: yes
                  
          
          #######################################################
          
      - name: oparte2.svg
        if: ${{ false }}
        uses: jackvvl/metrics@master
        with:
          user: jackvvl
          token: ${{ secrets.TOKEN_PERFIL }}
          committer_branch: main
          committer_message: Update ${filename} - [GitHub Action]
          config_timezone: America/Argentina
          
          config_display: columns          
          filename: parte2.svg
          config_output: svg

          base: ""
  
          
          #starred repositories
          plugin_stars: yes
          plugin_stars_limit: 2
          
          #topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          
          plugin_traffic: yes
          repositories_forks: yes
          
          #achivements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
