name: Metrics
on:
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics 1
        uses: jackvvl/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.TOKEN_PERFIL }}

          # Options
          filename: metrics1.svg
          user: jackvvl
          base: header, activity, repositories, metadata
          config_timezone: America/Argentina
          config_twemoji: yes
          
          
          #coding habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_trim: yes
          
          
          
          #languages
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 16
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes

 
 

      - name: Metrics 2
        uses: jackvvl/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.TOKEN_PERFIL }}

          # Options
          filename: metrics2.svg
          user: jackvvl
          base: ""
          config_timezone: America/Argentina
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          use_prebuilt_image: yes
